service=whostmgr
user=root
url=/cgi/help4_disk_usage/index.cgi
entryurl=help4_disk_usage/index.cgi
displayname=Help4 Disk Usage
acls=any
icon=help4-disk-usage.png
target=_self
searchtext=disk usage inode files cache logs quota accounts help4
